### ISSUE TITLE
Update templates to use .NET Platform Standard

### ISSUE THREAD

**Issue by martijn00** [jamesmontemagno/Xamarin-Templates#10]
We should update the templates and the plugin for VS to make use of the .NET Platform Standard.
https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

**Comment by jamesmontemagno** [comment]
Yeah... they need to do something like this:
PCLCrypto/1.0.80/ref/netstandard1.0/PCLCrypto.dll

I tried to convert some of my plugins and it was a nightmare. The tooling is just so early.

**Comment by martijn00** [comment]
In this case it might be quite simple. In visual studio you can update any PCL to a NET Standard lib by pressing the upgrade button on the properties of the project. After that we only need to change the nuspec to `ref` that new library instead of use it as `lib`.

It would get complex if you have other dependencies, or if you want to target a different standard, but i guess we could just go for 1.0 since Profile78 is used for the PCL. Or do you want to drop support for Silverlight projects?

**Comment by figursagsmats** [comment]
Any updates? The tooling is better now!

**Comment by jamesmontemagno** [comment]
Done
