### ISSUE TITLE
Extra dependencies added in Android

### ISSUE THREAD

**Issue by alexrainman** [jamesmontemagno/Xamarin-Templates#18]
James,

I am creating a plugin using your multi-target template and when i install the created nuget package, some dependencies that i don't want are added in Android.

Dependencies before installing package:

![screen shot 2018-05-10 at 2 27 26 pm](https://user-images.githubusercontent.com/3793554/39889883-bfcb362e-545e-11e8-86a4-e5de308e1b2f.png)

Dependencies after installing package:

![screen shot 2018-05-10 at 2 27 41 pm](https://user-images.githubusercontent.com/3793554/39889902-cb7b571a-545e-11e8-81a0-77bddefbf642.png)

These are added and some of them fail as you can see in the screenshot:

Java.Interop
System.Collections
System.IdentityModel
System.Runtime
System.Runtime.Serialization
System.Threadings.Tasks

How i can fix that?

Thanks

**Comment by jamesmontemagno** [comment]
Yes, simply update the SDK Tool to 1.4.0 instead of 1.2.0

**Comment by jamesmontemagno** [comment]
The nuget package that is brought in that is.

**Comment by alexrainman** [comment]
That was fast 👍

**Comment by jamesmontemagno** [comment]
I will be updating the templates soon :)

**Comment by alexrainman** [comment]
I updated the SDK. Java.Interop still there and the SDK Nuget is now installed on both Android and iOS but, everything works as expected.

Awesome work James.

**Comment by jamesmontemagno** [comment]
yeah, that one is okay :)

**Comment by alexrainman** [comment]
👍

**Comment by alexrainman** [comment]
James, can i use uap10.0.16299? I get lot of compilation errors.

**Comment by jamesmontemagno** [comment]
If you are on VS for Mac it doesn't support multi-targeting you need to use VS 2017

**Comment by alexrainman** [comment]
I am using VS 2017 but when i change the default 15063 you have on your template for 16299 then i get bunch of errors.

**Comment by jamesmontemagno** [comment]
You have to have that SDK installed and make sure you change it in all place. See: https://github.com/jamesmontemagno/SettingsPlugin/blob/master/src/Plugin.Settings/Plugin.Settings.csproj
