### ISSUE TITLE
Add UWP project to template

### ISSUE THREAD

**Issue by martijn00** [jamesmontemagno/Xamarin-Templates#2]

**Comment by jamesmontemagno** [comment]
Hmmm, not a bad idea, but will limit to 2015 development :( 

May need to create 2 packages, one for 2012/2013 and one for 2015. Thoughts?

**Comment by martijn00** [comment]
If you add this it will show as unsupported in VS2012/13 but those will still work with the existing project types. About the nuspecs: i think these can be altered to work with both.

**Comment by martijn00** [comment]
Shouldn't https://github.com/jamesmontemagno/Xamarin-Templates/tree/master/Plugins-Templates/Feature/Feature.Plugin.iOS be removed too? And the iOSUnified renamed to iOS?

**Comment by martijn00** [comment]
Have you thought on this?
