### ISSUE TITLE
**\*.android.cs , **\*.apple.cs , **\*.uwp.cs not loaded in the project

### ISSUE THREAD

**Issue by developingsyria** [jamesmontemagno/Xamarin-Templates#21]
I created a project using Plugin For Xamarin Templates, 
the project not include android, apple or uwp ( cs ) files,
I think the problem in Condition that used with ItemGroup, because when I removed the condition or set it to 1 == 1 it worked for every item group, 
Can you please help me.
i am using vs 2017 15.7.5

thank you.

**Comment by jamesmontemagno** [comment]
Do you have the UWP sdk installed for fall creators update? You can adjust your targets for what you actually have installed.

**Comment by developingsyria** [comment]
Hi James,
when I created Xamarin app with all platforms MonoAndroid80, IOS10 and uap10.0.16299 the app work well, but when created a plugin using xamarin plugin Template. it give the attached View

![feature](https://user-images.githubusercontent.com/20622550/42724338-ee642138-8778-11e8-9f07-00fa5bdf41ac.PNG)

beside when I removed the Condition attributes from Project XML file all  files of *.android.cs & *.uwp.cs & *.apple.cs loaded but with conflicting of TargetFramework, so I think something wrong with Condition.

when I installed VS 2017 Community version I installed all needed SDK, 
Is there any checking steps I need to do??

Thank you

**Comment by jamesmontemagno** [comment]
Also check if you have the .net core preview sdk installed if so then you should remove that as it is a bug in that sdk.

**Comment by developingsyria** [comment]
Thank you James, I removes the preview version of .net core SDK .
Now plugins working well.
thank you very very much.

**Comment by jamesmontemagno** [comment]
this was reported to the team over there and they should be fixing it up for stable release.
