### ISSUE TITLE
Creating projects with a period gives build errors in the project

### ISSUE THREAD

**Issue by rizanzaky** [jamesmontemagno/Xamarin-Templates#22]
When I select this **Plugin for Xamarin** template in Visual Studio 2017 to create a project, if I give in a name for the project with a period (".") **Ex:** Plugin.Cross, then the project fails to build mainly with `unexpected token errors`.

**Comment by egarim** [comment]
I have exactly the same problem

**Comment by jamesmontemagno** [comment]
Add a . is not supported it automatically adds Plugin. at the front
