### ISSUE TITLE
[Question] How to disable ShiftMode in BottomNavigation with Xamarin.Forms' renderers?

### ISSUE THREAD

**Issue by hugodantas** [jamesmontemagno/Xamarin-Templates#28]
Hi James... first of all, congratulations for the job you're doing to Xamarin Community.

I have one question. in [this](https://montemagno.com/remove-shifting-bottomnavigationview-android/) post on your blog, you teach how can we disable the item shift in the Xamarin.Android.. but how can I disable it from a Xamarin.Forms project? I cannot find the renderer to customize it permanently from Bottom TabbedPages.

Can you give us a light? 😄 

Thank you so much.

**Comment by jamesmontemagno** [comment]
It is not currently possible in Xamarin.Forms form my understanding I have an issue here: https://github.com/xamarin/Xamarin.Forms/issues/3083
