### ISSUE TITLE
Remove unnecessary iOS project 

### ISSUE THREAD

**Issue by martijn00** [jamesmontemagno/Xamarin-Templates#3]
Since Apple only supports unified projects i think it would be good to remove the old project type.

**Comment by jamesmontemagno** [comment]
Agreed, doing today.

**Comment by martijn00** [comment]
Shouldn't https://github.com/jamesmontemagno/Xamarin-Templates/tree/master/Plugins-Templates/Feature/Feature.Plugin.iOS be removed too? And the iOSUnified renamed to iOS?
