### ISSUE TITLE
How to create a Nuget-package for android class library?

### ISSUE THREAD

**Issue by AlexSchuetz** [jamesmontemagno/Xamarin-Templates#31]
Hi,
I created two PCL-projects and a Xamarin-Android-Class-Library project and want to deploy them to a private nuget repository.

For the PCL-projects I use to create nupkg-files:
```
<PackOnBuild>true</PackOnBuild>
<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
```
and this works fine.

For the android-class-library I tried the same, but with no effect.
When I call `msbuild \t:Pack MyProject.Android.csproj` it gives `error MSB4057: The target “pack” does not exist in the project`.

Can you give any advice? I am not familiar with the msbuild and nuget ecosystem and I am really stuck there.

**Comment by jamesmontemagno** [comment]
You would have to use the new SDK style project system such as: https://github.com/jamesmontemagno/CurrentActivityPlugin/blob/master/src/Plugin.CurrentActivity.Android/Plugin.CurrentActivity.Android.csproj
