### ISSUE TITLE
Missing MonoAndroid81 and Xamarin.iOS10

### ISSUE THREAD

**Issue by MartinRValdez** [jamesmontemagno/Xamarin-Templates#35]
I cant build my project =(

This is the error:

Severity	Code Description Project File	Line	Suppression State
Error The specified language targets for Xamarin.iOS10 is missing. Ensure correct tooling is installed for 'Xamarin.iOS'. Missing: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.CSharp.targets'

**Comment by jamesmontemagno** [comment]
I would recommend using: https://github.com/jamesmontemagno/plugin-template

**Comment by MartinRValdez** [comment]
@jamesmontemagno Thanks!!

**Comment by jamesmontemagno** [comment]
Just updated templates with latest stuff :)
