### ISSUE TITLE
Cannot create "Control Plugin for Xamarin.Forms" project.

### ISSUE THREAD

**Issue by csoren** [jamesmontemagno/Xamarin-Templates#6]
Using version 2.0.0 of the extension and Visual Studio 2015 Enterprise. These errors seem to indicate that perhaps I need to install some dependency, but pretty much every feature of VS2015 is installed and updated to the latest version.

Creating a project using the "Plugin for Xamarin" template Works fine, but "Control Plugin for Xamarin.Forms" gives two errors and leaves the project in a half-finished state. See the attached screenshots.

![error1](https://cloud.githubusercontent.com/assets/195392/14979128/a903536e-1120-11e6-9620-5b77f4ec2ed5.png)
![error2](https://cloud.githubusercontent.com/assets/195392/14979137/b0ad1172-1120-11e6-9ce9-14905b4bda04.png)

**Comment by logicmediadk** [comment]
+1 on this one.

Installed the extension today and tried to create a "Control Plugin for Xamarin.Forms" and the same problem as stated above happened.

**Comment by logicmediadk** [comment]
Manually adding the missing nuget package WPtoolkit.4.2013.8.16.nupkg to the folder specified solves part of the issue.

Note that the file has to be renamed since the original name from the repository is WPtoolkit.4.2013.08.16.nupkg.

I suspect this is also part of what is causing the problem with WP8.

**Comment by psharrma** [comment]
Hi @jamesmontemagno ,

I tried with suggested solution by @logicmediadk, it seems to resolve first issue. But i am still facing second issue w.r.t UWP project. Below is the message i receive:

---------------------------
Microsoft Visual Studio
---------------------------
A problem was encountered creating the sub project 'VLC.FormsPlugin.UWP'.  Unable to copy the file 'VLC.FormsPlugin.UWP.rd.xml' from the project template to the project. Cannot find file "E:\Temp\ah0cexer.qb1\Temp\Properties\VLC.FormsPlugin.UWP.rd.xml".
---------------------------
OK   
---------------------------

**Comment by jamesmontemagno** [comment]
No longer supported
