### ISSUE TITLE
Error APPX1101: Payload contains two or more files with the same destination path

### ISSUE THREAD

**Issue by poz1** [jamesmontemagno/Xamarin-Templates#8]
###### DESCRIPTION

Using the plugin template the Bait&Switch trick works fine on Android & iOS but not on UWP.
It seems that, for some reasons, it doesn't switch the PCL and then it doesn't know which one to use:

``` xml
1>------ Build started: Project: TestApp.UWP, Configuration: Debug x86 ------
1>  TestApp.UWP -> C:\Users\Alex\Source\Repos\TestFeature\TestApp\TestApp.UWP\bin\x86\Debug\TestApp.UWP.exe
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1683,5): error APPX1101: Payload contains two or more files with the same destination path 'Plugin.TestFeature.pdb'. Source files: 
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1683,5): error APPX1101: C:\Users\Alex\Source\Repos\TestFeature\TestFeature\Plugin.TestFeature.UWP\bin\Debug\Plugin.TestFeature.pdb
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1683,5): error APPX1101: C:\Users\Alex\Source\Repos\TestFeature\TestFeature\Plugin.TestFeature\bin\Debug\Plugin.TestFeature.pdb
========== Build: 0 succeeded, 1 failed, 4 up-to-date, 0 skipped ==========

```

---
###### PROJECT TO REPRODUCE THE ISSUE

[TestFeature](https://github.com/poz1/TestFeature)

**Comment by jasonCodesAway** [comment]
Hi @poz1. I'm glad I'm not the only one - I'm hitting this same problem. Have you found a workaround? Thanks!

**Comment by poz1** [comment]
Hey @jasonCodesAway!
Yes, try this:

UWP NOTICE

If in your exepriments you happen to get:

Error APPX1101: Payload contains two or more files with the same destination path

instead of referencing directly the project of the fake implementation add a reference directly to the dll and then set “Specific Version” to false.
This error will appear only if you reference “by hand“, if you try to create a Nuget from your project you’ll see the error disappear. This is because Nuget works directly with the ddls and not the projects

I posted about Bait & Switch on my blog but forgot to write it here :) 
http://www.poz1.com/baitswitch/

**Comment by jasonCodesAway** [comment]
Wow, thanks @poz1! I'm trying now but am having difficulty with my solution. The Xamarin learning curve (not code, but build issues like this) is proving to be most challenging.

**Comment by jasonCodesAway** [comment]
Argh. my solution is a big more complicated than the base case here. I've nominated you for the MVP, figure it's the least I can do since you're putting out very helpful blogs. I also sent you a LinkedIn request - I'm hoping you can help more directly for a fee. It is an open-source project.

**Comment by poz1** [comment]
Wrote you on Linkedin :) 
I think we can close this

**Comment by jasonCodesAway** [comment]
If anyone comes across this issue in the future please feel free to vote on this bug in Xamarin's bug tracking system (this is my best guess as to who owns this bug): https://bugzilla.xamarin.com/show_bug.cgi?id=44640
